- name: Build the image
  hosts: localhost
  connection: local
  vars:
    docker_port: 2375

  tasks:
    - include: docker_env_setup.yml

    - name: Build Docker Image
      docker_image:
        path='../'
        name='pep-visualize'
        state='present'
        docker_url='tcp://{{ docker_host.stdout }}:{{ docker_port }}'
